# Generated by Django 4.2.11 on 2024-05-01 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_comuna_region_delete_metadata_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrito',
            old_name='users_metadata',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='ordendecompra',
            old_name='users_metadata',
            new_name='user',
        ),
    ]
